// This file should be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <your-project-id> > lib/database.types.ts
//
// For now, this is a placeholder structure. Replace with actual generated types.

export interface Database {
  public: {
    Tables: {
      // Add your table definitions here
      // Example:
      // documents: {
      //   Row: {
      //     id: string;
      //     user_id: string;
      //     file_url: string;
      //     // ... other fields
      //   };
      //   Insert: {
      //     id?: string;
      //     user_id: string;
      //     file_url: string;
      //     // ... other fields
      //   };
      //   Update: {
      //     id?: string;
      //     user_id?: string;
      //     file_url?: string;
      //     // ... other fields
      //   };
      // };
    };
    Views: {
      // Add your view definitions here
    };
    Functions: {
      // Add your function definitions here
    };
    Enums: {
      // Add your enum definitions here
    };
  };
}
